name: CI

on:
  push:
    branches-ignore:
      - dev
      - master

jobs:
  build_and_preview:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build:staging --if-present
      - run: npm run lint
        # todo: add unit tests

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
            repoToken: '${{ secrets.GITHUB_TOKEN }}'
            firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ANYWAY_NEWSFLASH_INFOGRAPHICS }}'
            channelId: preview
            projectId: anyway-newsflash-infographics
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
          CI: true
